#!/usr/bin/env node
/**
 * Script to generate src/koans/index.js with all koans registered
 */

const fs = require('fs');
const path = require('path');
const glob = require('glob');

// Find all koan files
const koansDir = path.join(__dirname, '../src/koans');
const koanFiles = [
  ...glob.sync(`${koansDir}/pyspark/**/*.js`),
  ...glob.sync(`${koansDir}/delta/**/*.js`)
].filter(f => !f.includes('index.js'));

console.log(`Found ${koanFiles.length} koan files`);

// Parse koan files to get IDs and paths
let koans = [];
koanFiles.forEach(filePath => {
  const relativePath = path.relative(koansDir, filePath).replace(/\.js$/, '');
  const fileContent = fs.readFileSync(filePath, 'utf8');
  const idMatch = fileContent.match(/id:\s*(\d+)/);

  if (idMatch) {
    koans.push({
      id: parseInt(idMatch[1]),
      path: './' + relativePath,
      fileName: path.basename(filePath, '.js')
    });
  }
});

// Sort by ID
koans.sort((a, b) => a.id - b.id);

console.log(`Registering ${koans.length} koans (IDs: ${koans[0].id}-${koans[koans.length-1].id})`);

// Generate import statements
const imports = koans.map(k =>
  `import koan${k.id} from '${k.path}';`
).join('\n');

// Generate koansById object
const koansById = koans.map(k =>
  `  ${k.id}: koan${k.id},`
).join('\n');

// Generate index.js content
const indexContent = `/**
 * Central koan registry
 *
 * This file dynamically imports all koans and provides utilities
 * for accessing them by ID, category, etc.
 *
 * Auto-generated by scripts/generate-index.js
 */

${imports}

/**
 * All koans indexed by ID
 */
const koansById = {
${koansById}
};

/**
 * Get a koan by its ID
 */
export function getKoan(id) {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  return koansById[numId] || null;
}

/**
 * Get all koan IDs
 */
export function getAllKoanIds() {
  return Object.keys(koansById).map(id => parseInt(id, 10)).sort((a, b) => a - b);
}

/**
 * Get koans by category
 */
export function getKoansByCategory(category) {
  return Object.values(koansById)
    .filter(koan => koan.category === category)
    .sort((a, b) => a.id - b.id);
}

/**
 * Get all unique categories in logical learning order
 */
export function getAllCategories() {
  const categoryOrder = [
    'Basics',
    'Column Operations',
    'String Functions',
    'Aggregations',
    'Joins',
    'Window Functions',
    'Null Handling',
    'Advanced',
    'Complex Types',
    'Schemas',
    'Higher-Order Functions',
    'Testing',
    'Pandas Integration',
    'Structured Streaming',
    'Delta Lake'
  ];

  const categories = [...new Set(Object.values(koansById).map(k => k.category))];

  // Sort by custom order, with any unexpected categories at the end
  return categories.sort((a, b) => {
    const indexA = categoryOrder.indexOf(a);
    const indexB = categoryOrder.indexOf(b);

    // If both are in the order list, sort by their position
    if (indexA !== -1 && indexB !== -1) return indexA - indexB;

    // If only A is in the list, it comes first
    if (indexA !== -1) return -1;

    // If only B is in the list, it comes first
    if (indexB !== -1) return 1;

    // If neither is in the list, alphabetical
    return a.localeCompare(b);
  });
}

/**
 * Get koan statistics
 */
export function getKoanStats() {
  const koans = Object.values(koansById);
  return {
    total: koans.length,
    byCategory: koans.reduce((acc, koan) => {
      acc[koan.category] = (acc[koan.category] || 0) + 1;
      return acc;
    }, {}),
    byDifficulty: koans.reduce((acc, koan) => {
      acc[koan.difficulty] = (acc[koan.difficulty] || 0) + 1;
      return acc;
    }, {}),
  };
}

export default koansById;
`;

// Write index.js
const indexPath = path.join(koansDir, 'index.js');
fs.writeFileSync(indexPath, indexContent);

console.log(`\n✓ Generated ${indexPath}`);
console.log(`✓ Registered ${koans.length} koans`);
