/**
 * Central koan registry
 *
 * This file dynamically imports all koans and provides utilities
 * for accessing them by ID, category, etc.
 *
 * Auto-generated by scripts/generate-index.js
 */

import koan1 from './pyspark/basics/koan-001-create-dataframe';
import koan2 from './pyspark/basics/koan-002-select-columns';
import koan3 from './pyspark/basics/koan-003-filter-rows';
import koan4 from './pyspark/basics/koan-004-add-columns';
import koan5 from './pyspark/basics/koan-005-groupby-agg';
import koan6 from './pyspark/basics/koan-006-dropping-columns';
import koan7 from './pyspark/basics/koan-007-distinct-values';
import koan9 from './pyspark/column-ops/koan-009-renaming-columns';
import koan10 from './pyspark/column-ops/koan-010-literal-values';
import koan11 from './pyspark/column-ops/koan-011-conditional-logic-with-when-otherwise';
import koan12 from './pyspark/column-ops/koan-012-type-casting';
import koan13 from './pyspark/strings/koan-013-string-functions-case';
import koan14 from './pyspark/strings/koan-014-string-functions-concatenation';
import koan15 from './pyspark/strings/koan-015-string-functions-substring-and-length';
import koan16 from './pyspark/strings/koan-016-string-functions-trim-and-pad';
import koan17 from './pyspark/aggregations/koan-017-grouping-and-aggregating';
import koan18 from './pyspark/aggregations/koan-018-multiple-aggregations';
import koan19 from './pyspark/aggregations/koan-019-aggregate-without-grouping';
import koan20 from './pyspark/joins/koan-020-inner-join';
import koan21 from './pyspark/joins/koan-021-left-outer-join';
import koan22 from './pyspark/joins/koan-022-join-on-multiple-columns';
import koan23 from './pyspark/windows/koan-023-window-functions-running-total';
import koan24 from './pyspark/windows/koan-024-window-functions-row-number';
import koan25 from './pyspark/windows/koan-025-window-functions-lag-and-lead';
import koan26 from './pyspark/nulls/koan-026-handling-nulls-detection';
import koan27 from './pyspark/nulls/koan-027-handling-nulls-fill-and-drop';
import koan28 from './pyspark/advanced/koan-028-union-dataframes';
import koan29 from './pyspark/advanced/koan-029-explode-arrays';
import koan30 from './pyspark/advanced/koan-030-pivot-tables';
import koan101 from './delta/koan-101-create-table';
import koan102 from './delta/koan-102-time-travel-version';
import koan103 from './delta/koan-103-merge-upsert-pattern';
import koan104 from './delta/koan-104-merge-selective-update';
import koan105 from './delta/koan-105-table-history';
import koan106 from './delta/koan-106-optimize-and-z-order';
import koan107 from './delta/koan-107-delete-with-condition';
import koan108 from './delta/koan-108-update-with-condition';
import koan109 from './delta/koan-109-create-table-with-builder';
import koan110 from './delta/koan-110-vacuum-old-files';
import koan201 from './pyspark/complex-types/koan-201-nested-structs';
import koan202 from './pyspark/complex-types/koan-202-map-types';
import koan203 from './pyspark/complex-types/koan-203-array-of-structs';
import koan204 from './pyspark/schemas/koan-204-defining-schemas';
import koan205 from './pyspark/schemas/koan-205-schema-enforcement';
import koan206 from './pyspark/higher-order/koan-206-transform';
import koan207 from './pyspark/higher-order/koan-207-filter-arrays';
import koan208 from './pyspark/higher-order/koan-208-aggregate-arrays';
import koan209 from './pyspark/testing/koan-209-assert-dataframe-equal';
import koan210 from './pyspark/testing/koan-210-assert-dataframe-advanced';
import koan211 from './pyspark/testing/koan-211-assert-schema-equal';
import koan212 from './pyspark/testing/koan-212-testing-patterns';
import koan213 from './pyspark/pandas-integration/koan-213-topandas-and-back';
import koan214 from './pyspark/pandas-integration/koan-214-pandas-udf-scalar';
import koan215 from './pyspark/pandas-integration/koan-215-apply-in-pandas';
import koan216 from './pyspark/pandas-integration/koan-216-map-in-pandas';
import koan217 from './pyspark/streaming/koan-217-rate-source';
import koan218 from './pyspark/streaming/koan-218-datastreamreader';
import koan219 from './pyspark/streaming/koan-219-streaming-transformations';
import koan220 from './pyspark/streaming/koan-220-streaming-queries';
import koan221 from './pyspark/streaming/koan-221-stream-triggers';
import koan222 from './pyspark/streaming/koan-222-monitoring-streams';
import koan223 from './pyspark/streaming/koan-223-sliding-windows';
import koan224 from './pyspark/streaming/koan-224-transform-with-state';

/**
 * All koans indexed by ID
 */
const koansById = {
  1: koan1,
  2: koan2,
  3: koan3,
  4: koan4,
  5: koan5,
  6: koan6,
  7: koan7,
  9: koan9,
  10: koan10,
  11: koan11,
  12: koan12,
  13: koan13,
  14: koan14,
  15: koan15,
  16: koan16,
  17: koan17,
  18: koan18,
  19: koan19,
  20: koan20,
  21: koan21,
  22: koan22,
  23: koan23,
  24: koan24,
  25: koan25,
  26: koan26,
  27: koan27,
  28: koan28,
  29: koan29,
  30: koan30,
  101: koan101,
  102: koan102,
  103: koan103,
  104: koan104,
  105: koan105,
  106: koan106,
  107: koan107,
  108: koan108,
  109: koan109,
  110: koan110,
  201: koan201,
  202: koan202,
  203: koan203,
  204: koan204,
  205: koan205,
  206: koan206,
  207: koan207,
  208: koan208,
  209: koan209,
  210: koan210,
  211: koan211,
  212: koan212,
  213: koan213,
  214: koan214,
  215: koan215,
  216: koan216,
  217: koan217,
  218: koan218,
  219: koan219,
  220: koan220,
  221: koan221,
  222: koan222,
  223: koan223,
  224: koan224,
};

/**
 * Get a koan by its ID
 */
export function getKoan(id) {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  return koansById[numId] || null;
}

/**
 * Get all koan IDs
 */
export function getAllKoanIds() {
  return Object.keys(koansById).map(id => parseInt(id, 10)).sort((a, b) => a - b);
}

/**
 * Get koans by category
 */
export function getKoansByCategory(category) {
  return Object.values(koansById)
    .filter(koan => koan.category === category)
    .sort((a, b) => a.id - b.id);
}

/**
 * Get all unique categories in logical learning order
 */
export function getAllCategories() {
  const categoryOrder = [
    'Basics',
    'Column Operations',
    'String Functions',
    'Aggregations',
    'Joins',
    'Window Functions',
    'Null Handling',
    'Advanced',
    'Complex Types',
    'Schemas',
    'Higher-Order Functions',
    'Testing',
    'Pandas Integration',
    'Structured Streaming',
    'Delta Lake'
  ];

  const categories = [...new Set(Object.values(koansById).map(k => k.category))];

  // Sort by custom order, with any unexpected categories at the end
  return categories.sort((a, b) => {
    const indexA = categoryOrder.indexOf(a);
    const indexB = categoryOrder.indexOf(b);

    // If both are in the order list, sort by their position
    if (indexA !== -1 && indexB !== -1) return indexA - indexB;

    // If only A is in the list, it comes first
    if (indexA !== -1) return -1;

    // If only B is in the list, it comes first
    if (indexB !== -1) return 1;

    // If neither is in the list, alphabetical
    return a.localeCompare(b);
  });
}

/**
 * Get koan statistics
 */
export function getKoanStats() {
  const koans = Object.values(koansById);
  return {
    total: koans.length,
    byCategory: koans.reduce((acc, koan) => {
      acc[koan.category] = (acc[koan.category] || 0) + 1;
      return acc;
    }, {}),
    byDifficulty: koans.reduce((acc, koan) => {
      acc[koan.difficulty] = (acc[koan.difficulty] || 0) + 1;
      return acc;
    }, {}),
  };
}

/**
 * Track definitions
 * Standard: IDs 1-99 (PySpark basics) + 101-199 (Delta Lake)
 * Advanced: IDs 200+ (advanced topics)
 */
export const TRACKS = {
  standard: {
    name: 'PySpark Fundamentals',
    description: 'Master the core PySpark and Delta Lake APIs',
    badge: '/assets/badges/pyspark-fundamentals.png',
    badgePage: '/badge',
    startKoan: 1,
    filter: (id) => id < 200,
  },
  advanced: {
    name: 'PySpark Advanced',
    description: 'Complex types, testing, pandas integration, and streaming',
    badge: '/assets/badges/pyspark-advanced.png',
    badgePage: '/badge/advanced',
    startKoan: 201,
    filter: (id) => id >= 200,
  },
};

/**
 * Get the track for a given koan ID
 */
export function getTrackForKoan(id) {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  if (numId >= 200) return 'advanced';
  return 'standard';
}

/**
 * Get all koan IDs for a specific track
 */
export function getKoanIdsByTrack(track) {
  const trackDef = TRACKS[track];
  if (!trackDef) return getAllKoanIds();
  return getAllKoanIds().filter(trackDef.filter);
}

/**
 * Get categories for a specific track
 */
export function getCategoriesByTrack(track) {
  const ids = new Set(getKoanIdsByTrack(track));
  const trackKoans = Object.values(koansById).filter(k => ids.has(k.id));
  const categories = [...new Set(trackKoans.map(k => k.category))];

  return getAllCategories().filter(c => categories.includes(c));
}

/**
 * Get koan stats for a specific track
 */
export function getTrackStats(track) {
  const ids = new Set(getKoanIdsByTrack(track));
  const koans = Object.values(koansById).filter(k => ids.has(k.id));
  return {
    total: koans.length,
    byCategory: koans.reduce((acc, koan) => {
      acc[koan.category] = (acc[koan.category] || 0) + 1;
      return acc;
    }, {}),
  };
}

export default koansById;
