/**
 * Central koan registry
 *
 * This file dynamically imports all koans and provides utilities
 * for accessing them by ID, category, etc.
 *
 * Auto-generated by scripts/generate-index.js
 */

import koan1 from './pyspark/basics/koan-001-create-dataframe';
import koan2 from './pyspark/basics/koan-002-select-columns';
import koan3 from './pyspark/basics/koan-003-filter-rows';
import koan4 from './pyspark/basics/koan-004-add-columns';
import koan5 from './pyspark/basics/koan-005-groupby-agg';
import koan6 from './pyspark/basics/koan-006-dropping-columns';
import koan7 from './pyspark/basics/koan-007-distinct-values';
import koan9 from './pyspark/column-ops/koan-009-renaming-columns';
import koan10 from './pyspark/column-ops/koan-010-literal-values';
import koan11 from './pyspark/column-ops/koan-011-conditional-logic-with-when-otherwise';
import koan12 from './pyspark/column-ops/koan-012-type-casting';
import koan13 from './pyspark/strings/koan-013-string-functions-case';
import koan14 from './pyspark/strings/koan-014-string-functions-concatenation';
import koan15 from './pyspark/strings/koan-015-string-functions-substring-and-length';
import koan16 from './pyspark/strings/koan-016-string-functions-trim-and-pad';
import koan17 from './pyspark/aggregations/koan-017-grouping-and-aggregating';
import koan18 from './pyspark/aggregations/koan-018-multiple-aggregations';
import koan19 from './pyspark/aggregations/koan-019-aggregate-without-grouping';
import koan20 from './pyspark/joins/koan-020-inner-join';
import koan21 from './pyspark/joins/koan-021-left-outer-join';
import koan22 from './pyspark/joins/koan-022-join-on-multiple-columns';
import koan23 from './pyspark/windows/koan-023-window-functions-running-total';
import koan24 from './pyspark/windows/koan-024-window-functions-row-number';
import koan25 from './pyspark/windows/koan-025-window-functions-lag-and-lead';
import koan26 from './pyspark/nulls/koan-026-handling-nulls-detection';
import koan27 from './pyspark/nulls/koan-027-handling-nulls-fill-and-drop';
import koan28 from './pyspark/advanced/koan-028-union-dataframes';
import koan29 from './pyspark/advanced/koan-029-explode-arrays';
import koan30 from './pyspark/advanced/koan-030-pivot-tables';
import koan101 from './delta/koan-101-create-table';
import koan102 from './delta/koan-102-time-travel-version';
import koan103 from './delta/koan-103-merge-upsert-pattern';
import koan104 from './delta/koan-104-merge-selective-update';
import koan105 from './delta/koan-105-table-history';
import koan106 from './delta/koan-106-optimize-and-z-order';
import koan107 from './delta/koan-107-delete-with-condition';
import koan108 from './delta/koan-108-update-with-condition';
import koan109 from './delta/koan-109-create-table-with-builder';
import koan110 from './delta/koan-110-vacuum-old-files';

/**
 * All koans indexed by ID
 */
const koansById = {
  1: koan1,
  2: koan2,
  3: koan3,
  4: koan4,
  5: koan5,
  6: koan6,
  7: koan7,
  9: koan9,
  10: koan10,
  11: koan11,
  12: koan12,
  13: koan13,
  14: koan14,
  15: koan15,
  16: koan16,
  17: koan17,
  18: koan18,
  19: koan19,
  20: koan20,
  21: koan21,
  22: koan22,
  23: koan23,
  24: koan24,
  25: koan25,
  26: koan26,
  27: koan27,
  28: koan28,
  29: koan29,
  30: koan30,
  101: koan101,
  102: koan102,
  103: koan103,
  104: koan104,
  105: koan105,
  106: koan106,
  107: koan107,
  108: koan108,
  109: koan109,
  110: koan110,
};

/**
 * Get a koan by its ID
 */
export function getKoan(id) {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  return koansById[numId] || null;
}

/**
 * Get all koan IDs
 */
export function getAllKoanIds() {
  return Object.keys(koansById).map(id => parseInt(id, 10)).sort((a, b) => a - b);
}

/**
 * Get koans by category
 */
export function getKoansByCategory(category) {
  return Object.values(koansById)
    .filter(koan => koan.category === category)
    .sort((a, b) => a.id - b.id);
}

/**
 * Get all unique categories in logical learning order
 */
export function getAllCategories() {
  const categoryOrder = [
    'Basics',
    'Column Operations',
    'String Functions',
    'Aggregations',
    'Joins',
    'Window Functions',
    'Null Handling',
    'Advanced',
    'Delta Lake'
  ];

  const categories = [...new Set(Object.values(koansById).map(k => k.category))];

  // Sort by custom order, with any unexpected categories at the end
  return categories.sort((a, b) => {
    const indexA = categoryOrder.indexOf(a);
    const indexB = categoryOrder.indexOf(b);

    // If both are in the order list, sort by their position
    if (indexA !== -1 && indexB !== -1) return indexA - indexB;

    // If only A is in the list, it comes first
    if (indexA !== -1) return -1;

    // If only B is in the list, it comes first
    if (indexB !== -1) return 1;

    // If neither is in the list, alphabetical
    return a.localeCompare(b);
  });
}

/**
 * Get koan statistics
 */
export function getKoanStats() {
  const koans = Object.values(koansById);
  return {
    total: koans.length,
    byCategory: koans.reduce((acc, koan) => {
      acc[koan.category] = (acc[koan.category] || 0) + 1;
      return acc;
    }, {}),
    byDifficulty: koans.reduce((acc, koan) => {
      acc[koan.difficulty] = (acc[koan.difficulty] || 0) + 1;
      return acc;
    }, {}),
  };
}

/**
 * Get koan IDs by categories
 * @param {Array<string>} categories - Array of category names
 * @returns {Array<number>} Sorted array of koan IDs
 */
export function getKoanIdsByCategories(categories) {
  if (!categories || categories.length === 0) {
    return [];
  }

  return Object.values(koansById)
    .filter(koan => categories.includes(koan.category))
    .map(koan => koan.id)
    .sort((a, b) => a - b);
}

/**
 * Get koans filtered by exam coverage
 * @param {string} examCode - Exam code (e.g., 'DEA', 'DAA', 'MLA')
 * @returns {Array<number>} Sorted array of koan IDs
 */
export function getKoanIdsByExamCoverage(examCode) {
  return Object.values(koansById)
    .filter(koan => koan.examCoverage && koan.examCoverage.includes(examCode))
    .map(koan => koan.id)
    .sort((a, b) => a - b);
}

export default koansById;
